import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "../components/BottomNav";
import { PlanProvider } from "./context/PlanContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <PlanProvider>
          {children}
          <BottomNav />
        </PlanProvider>
      </body>
    </html>
  );
}
